spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:evpaassen/scc-config-a.git
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIJJwIBAAKCAgEArxgcYggvomWVg/Q0yOd/ykdreoDyyPgeO3mnqoiCBOPYAqu7
            PpMtGMeqYUx8tDPJwiv73ZMgrjRN6HmgaG8vMaf0s0eRBj2CqhljlbwNolptlnjM
            xsWheC02e3mbMT8fVdtsiX88Pf+2w0W3bm0Ci2+ywX1gvQP3oKHtuSFDkq2cfAk3
            UU+qOoHiNXOu/5F/SFRDnCFDcuSHKQ7r1FjTfLOqAxGUDpYGMcY797hbbSge6EKy
            rxqHaggaj2ElcIGOg2nKPX+YbB1zknyn1kwNQjCV/Kq5scbtH9WyUlp9fG5cd/vS
            81T71ddkxgBF1SBDb0bGWt8lZyUHD0ol+n5bJkrF6thsLcM0HHYS9doa6sHAnDLD
            rZbIpH4vveEsExMl1YIljA4xtH/L/kSHJwJ4r59Tm7X3ViSy/vOBwzfaRRE8UrZT
            68rcao9wr14FWZfaI2RTI7vXn2h5htFu8phI6ZNPGNQNn9pu4QS+mw4VsiaD8wPy
            KEAKBPkagP9l0DpAOP7n+hnUSQB3F8WoTD4mutUt5ZsMPstZPdVtwUwjZFORJRqA
            UZ++Atpg65BgsXqSsyaK4iJLwnESZ8x+UZv6NS4efx6VNf2mMU/Gs9o2aBaRnd/c
            zSH/h9f6TibN9A/XGxGOxjWflP69Md9CpxGANZc/N940vyRTwdfmHTPcaCkCAwEA
            AQKCAgA8NuR76ijHhnvWt0L33HUcEVeq93GHH5z2Ay5f/TYJjHma4YgxStf1b6Tu
            dSllp3G5LvsdBh31CtPIIRvDDomCYCpNBU2ggcLP0I9ozRU7QjHxz3VM3mZbN+FG
            sVlnpDeYhS9cUb9b6vblTLJ6bU60uSMWW5HLLvQX79gbFI9yf/YSyfCWK/l0yXoL
            u87w4Q6OxzvBE8doWaMJwbHkgu+oMPlEuOTb50gWEgBJfsMiVOvcICPnCA6Nrl/D
            8zq26DckhlsgryKx+6blN61Yiyr8Gk1aaTQXKTwe+JSssaX6BtISCS5QtGcu8TYc
            ybc6RjAqsoJAegEY6aj13yAUdyPNA75C52KYUCBvqK/yNqAlYrQxv+w9bRpU6Rku
            Y3mWf59G+LCnbb3NmXcG4C1jiQa9a35kV3TWXN5y0Nl8JiFqLJrRd4Qwi2oIuGAs
            uKoYZAwakvVOu/5HDFtblAGNB3WCqNpLbIxGCABW4KsDb93OMjZ0pZH2VsUZQ7cS
            C/MT9geAcssYyqocIM5oHtkdAAh54QsIbdt6CVfgeljsfikutKGLiQHk0e1ANgXd
            8Q1w61vmVDZLD2cfB/LT1Mu+DoKC1uKrb60KqPFrUZCVHtlV99+SlJ+6fk66tQhv
            n1wNYwdj8WRm+z7QAEsbvsP308FSd1e3naRauSQ3wS3SlbHZIQKCAQEA2GdutfIW
            U9e2lzB6j0SsfVhX8gRDTzm+g/YjDR4VReVFu0zQefwHtm+/nHrY7YqQG23YYfVX
            pMPPIa7k1IbHC0uLGXDhnEO8dtUlw+ojY77S1URIeqfsx8tDxEjMIQpOm4YB+htz
            Z49VLvjGQ/SYvcryyXRO6znSehBzlOfMpqaWXgaxrN/zOgjzz6zR1/TC4Wir7uZP
            mKRJ6zw+g/j2/gNV8qLriK4i/n9l19Kh/8UVP09Ab9qKis/yGWG08XktWTDuZHq6
            KhDhEO/9yuEdv/SDDQQp3yeIHmhf7WCEoxC1ezyGnAQlYp20pGDa0vxuvJdebTUb
            QzpWcimnCRO4FQKCAQEAzyGvtOrolX6cyb1OWerBuNCfzUa/tCBbOjIRinlUlyR0
            Jyv3l+A4aisO5CedROfe7Xdnnt7I2Fck7GBuTkWzEU+CdToAH2/99xEb9ZRCeB3I
            pwx5grDyXWkWvMNF9oupI6oN78fYTRcgDaK1kO+e2YGPqh3wIYwFx5JKQ4T9OdPx
            4qbEpVnZY1rAjxUJZBDTPyiNAv8/ihnRsz9QOU0Pmu3sejLLbvoKqpVxYOtE+Dcq
            Fvo24l+bjDAEEpMBGIolx6Td3uCNEasedf9Gurqq/HojS35kcpqmp0rdHt/xshlZ
            VW/j3zzZpCEreOc4cwYaTzz6EhBVSJaO7xbPfyDAxQKCAQAPDqNVZZLIIqpBus3M
            Sir2Tb9Qx5snWA05gVbPAtjYFCvV7HJVCoQ+3Wenq6SMYqfEQNBdgISoojc3UMP7
            RaVz073J92C7Trs+SXZnO1NbDVv+GtIwNp7zB+GfNrF9Wwo9KAXbMS3GduKmcgjZ
            kZtPGV/rRHx5QXyzoZFpOveyYMT1peGW9b4mu5i7SnsPW6hzpqTP6pZ/OG8sPvTa
            megVpIXGbC+XQwaMTrD3Y2CCO2RPE2SYY8xf/DgMLBA6/QN6wTzVIPTzGFmQpCI0
            i5VWVd0IetGvBUEjXH/QNHcGIZN/D6cOE/vF8NMw3MxdAdNyq9WWI6vR8a0yJFPK
            /eRBAoIBABzIbpUya32SqZDzKHcgQyk+fGZXJX6PXH36xSs77wBNxYJH/tDxDIXc
            U+ZqhtUzb2wKQrD1/mzptyzNvaZM0zRdmyBVHf1AX8c8bmky4AW3BdIIzr3Vfuhy
            GQHEFO3MvIVDNUqTt8AGraKXcKmiUq2g7mjSXjMbNRZlgsJdMZ8ej6dSS1M66BWB
            X+7CGpr4J5LIPMgk1hyHt/cznh9IURnTZCAa/OAACQlpWOcB6oSfjc7BmGzeokvZ
            xEccfHN/hv52L4qwI4pIACSfg6GhHO+WvV7ZQnYWfYATzCRlND3ufdZ8hOrZltjS
            7yqO3u5E89T9ATcPY/qBSX156v2cfI0CggEAda4YuE3vnBA46s8MO98uMK3wagbp
            f2W1BjR1spBJv6Pkt77l+JQqMDkFEh3sOSFBRqDQbqmTFf8up1dKn/FA1Q9+NA91
            oBz+faVV5f4pvhQrEWHiujYl2LzFa8Qp4epC5AuWgjEV2cfAXuGR4g5R7eYXQroD
            wiwSpJFGarZ+/i+gQct/QP4SjCApIbQCgQFvyuQIFuZvkNZhxKMdkJY3S15iy1u2
            DAP7jpbX0MgTEcOcAqztOkQ/r1pdc3yy1Zk2h1TRu3UsqlmIt+j+zUNQ2TRL5a1J
            KZHY2Ty2t4JlfkmilzugFR7ADaXvO1++xyEMx4t9RzClbJSukG60fSPRew==
            -----END RSA PRIVATE KEY-----
          repos:
            repo-b:
              pattern: b/*
              uri: git@github.com:evpaassen/scc-config-b.git
              ignore-local-ssh-settings: true
              private-key: |
                -----BEGIN RSA PRIVATE KEY-----
                MIIJKQIBAAKCAgEA1MyJU9FV3f0UqiAcax88VVZMkE6APbJ0XJParx3RtjpLlE1h
                775Iei/V7QYdsj+xQlXhi1RJoFlo6jXH2sDXG3DU2tfg+nboiF70M7jat3HDatZP
                QgPJfwRheSXnsbzNQgalImo256ZK7s2HII7NYhPkxRybPAVbUCgQ1ptHLOB5nJzk
                2nGrq/iX6ZBPqPM25eFIc/1b+rvbGWKKvr0iOuQgzWi7pnPi352cYCFSQN/+7Piv
                +YUEIGX/CkCxoTVfJbbFcx8JfCkiBLUJCz3BbRq3OEb4lgaJ0Q1xur2U0Ii47Cpx
                TALpColl24+TNi3EDoaxSRHLioqEO+J42pZ/K8xTnn/e03duKBBFHJYgQdPYitlL
                o2Cm7rJ9a5RPmh7YdGA/R6XnPSiCNV/TUyua4KVljdzFLE76PVgdTOpeDwlzltE4
                p1TSjOsT0+61vvGsXkyc480x2jEjJ1m0cLPVSjQBYgWnxoLD3pDHaHlds1RDMvgZ
                Am542iuqsVi22D1WWv4heU9JUvCq3Q95hrOqy3oBxP5LxfO16/YbXg8xgAR3CZha
                U9PJ42MXg+RMhAxlswf+658u+8Nj8Wvr74pJLxjBfE0EFuaHEE7eHx49hEIEP/RP
                4tqMkIIHhDgRm1BzzcnCkCDTLmN5il0MQcur0QfxYProFhTyp9TdiXdQUrMCAwEA
                AQKCAgEAgF0lVb9ICdG5XmpiWigMb/nP05jW+OCmGpZB6zKUp1UA9GO9eS4ScEpc
                xE7VKQoMtlQx6qcchrKIfAeXGBkNaQsmCyEAIHYMDP8iVfTjUpc4Z0EBrHO2X31Y
                AwlfezLFqldx05G4rwH735NxOK2LrOcNL+3yokEk9PRGO/6M78A0+8kUr8Sz5tfd
                Y1HfC64y5naACx/BFT2ui+CKi0Zx2I52TxInZ+At8fAUPVS8VlAIahAVrvGTLKv6
                LcganoEgdRKMhsYpJZF2aNp/qx1Eibj83uDI4U7uYYG3ogrsMuLWkfeEQnLa+rUp
                EUnJZnwy8QRE+yvV2St3WtxhRJJWAQ7J/D1YNM4ESAzxyEHruhniOBIvdkxRUvtr
                8UkcK3uIls1IUf3IqLqtrVOzFbAdtoyhlI7nLOps1RUCQIB7TpfI9cmDumJDvt5Y
                1ovtFYlbrKlJ4j1RsR5xXPICc9I1YLhMe3VA0hj8GYIXrne9j6OYfBwlcsq1hc1F
                Z/lxnYbs6cQyLcJo/4ETQzJa8llc4Edjiw66j7YIdJJxKnvKYKHIlrU7HGiXcZ5l
                hPwLkE34sQ6AAdcbSqEDv0nMpUDhfVhjW33NCHqZksn83yeRfNbVbFsWTKNbD9gG
                FtQFQ93EjIdQjTTJ6fLJSte30IngIUYwjIAutbYr9d8IFqXyvBkCggEBAPHztxlP
                BoW7o35urfcjWH/utwKqZK4pbMMF0BGdbfARhdThvKrhEJlKZiXoXo2L1acrjK0J
                A6cBZ3jk5AD69aRhkkIXcoPTsY8BV/+kU45fChMXfGNMc8S+BsoGYmD1HWK9wWO7
                iNMKNohkIx/BKMomoe+JCIdwa0CN6aqvtDxO5ZFIPtuSrF9MJiQyfY+vsIPXcExR
                xEzawo6j2a2ZPRUAn0rXdfU1lobsEebTaEMWbRCwsipNv0d3wnIPYB35O7SwPLoj
                Bp2wapEYgYgexDL8/XKfm9QK89FWKQmy/vBPdXg8ZYfVxgwc4EiSVkgZDsZ6srA1
                MwW1N1+BLG4LWVUCggEBAOEngFA5d4Q7slMnpdcmo9wrwyrmYBSUI0om7GCk8hDs
                kNswejbs+wt4IAhovdoZE2i8iDm91Kg+4PWPG7y2kblO05S/SGywB0vID4pPYAON
                bKT5RmSrtMOu2xulwV0HNDidDPbuxvHOtjuGPfPBrSGTO95jwTN5s4JjO6Ouurut
                1p3mztYtNOAOeTwk1V9hT+Q1rFc63qW1dp0KjXknZuS0hQJjjzmlixxtHKT+TY3s
                A9yh1Chw4uK6ER0M6CEEAogZfG/ZZrKFHE/69EW/TBXGNGSYjyCDpo1Pf3Gck50l
                XBg4kN1WzhMtxT0Um4XZLhXbqCron0e46nImLyML2+cCggEBAJ/SyME8FWfjkdUj
                kWDuBTjE3DkzizwMex68STxJjOSG/qunzbPm5csMfTtPKp4/n4tE1jE7AiGgaNRQ
                BlirbfX+ydlEmc2A2gpH7fQdfWBPYV1JJ06Eovh0OhHbc8LuR1IBXKzfpTsaxPkF
                hLomIyadrFyJXYvx87b5xz+LvvgTeculOHhcg+aTa6J/g7eVa3k7p5+SZ6QI4XnN
                vC3TSqkD9zU97Fpk4qEPcafTQE0IlFTxE0+kedTgxB4KEAjcqNbrj8G4/1bMwShF
                UtMy15GC0nyT+CByd6pxSrxwc70UD9mzs7GtwZwguvrVR49qlfr/8+c3zRNZKFG7
                BzlN390CggEAKfVHhyu+ZwkM6UwpLpgHzz7khvkZjJwym133jOcQKTE8qWw2SkgN
                XIzNQ2PphVxI7qq7pC8JEzVsjLZXj+ph66uR6FVhNMf1BB1LMBYsqVzQk0nU4WvS
                KulJ8bQI/cIa7DXwNZA3yNYhxaP1pZhBIFGkxYPHfEVAu5qsgYtNRy5VIWXiw6z2
                /o4T765ZiQXEcp3B+RuCZFUVvpw50wsRtKsjYleVWEPOUcTPoru1Ti5eZd5OgB7R
                WTkdeVFvbL+njR9avilAZyJBLXJx1RGaJzChkOGRQpjmD81xzYVFSPKuX+Eitey4
                SICuEfzmIqJfYTlm9GAXVrFSF2WgQSKznwKCAQBvaCJAMUKSgyjXTYD1KznYEbul
                UVoMTrS5mnpeprbAm+Ko4amcJ0FMe6Svcn5MzG5ZK2UmZGcyofkjYYMtEAJSDa8f
                uoXAWZ0EjOPiqtAZ2AJ5idRLRMOrLU5glPFTYLaIIW6hfi3m8zhdgQgFgQuISQrn
                xqmgxOX504G00bI9++lOXM2Whho15w0iDJ1JCYMUxu5OpSqMVTm1kx0mvbNeyWzA
                9Hx6GbrdR0kXng+HRHOgGdCcVrQR5VwWK7vf6s4Ul2ZN2ZfsiH8P/HSqCxYJAZgQ
                QRA+zPJMseOp2u9ch2eiODzpKyzuqmHpNwpivi8XZZIftF5no8sOIRh8po8a
                -----END RSA PRIVATE KEY-----
#            repo-a:
#              pattern: a/*
#              uri: git@github.com:evpaassen/scc-config-a.git
#              ignore-local-ssh-settings: true
#              private-key: |
#                -----BEGIN RSA PRIVATE KEY-----
#                MIIJJwIBAAKCAgEArxgcYggvomWVg/Q0yOd/ykdreoDyyPgeO3mnqoiCBOPYAqu7
#                PpMtGMeqYUx8tDPJwiv73ZMgrjRN6HmgaG8vMaf0s0eRBj2CqhljlbwNolptlnjM
#                xsWheC02e3mbMT8fVdtsiX88Pf+2w0W3bm0Ci2+ywX1gvQP3oKHtuSFDkq2cfAk3
#                UU+qOoHiNXOu/5F/SFRDnCFDcuSHKQ7r1FjTfLOqAxGUDpYGMcY797hbbSge6EKy
#                rxqHaggaj2ElcIGOg2nKPX+YbB1zknyn1kwNQjCV/Kq5scbtH9WyUlp9fG5cd/vS
#                81T71ddkxgBF1SBDb0bGWt8lZyUHD0ol+n5bJkrF6thsLcM0HHYS9doa6sHAnDLD
#                rZbIpH4vveEsExMl1YIljA4xtH/L/kSHJwJ4r59Tm7X3ViSy/vOBwzfaRRE8UrZT
#                68rcao9wr14FWZfaI2RTI7vXn2h5htFu8phI6ZNPGNQNn9pu4QS+mw4VsiaD8wPy
#                KEAKBPkagP9l0DpAOP7n+hnUSQB3F8WoTD4mutUt5ZsMPstZPdVtwUwjZFORJRqA
#                UZ++Atpg65BgsXqSsyaK4iJLwnESZ8x+UZv6NS4efx6VNf2mMU/Gs9o2aBaRnd/c
#                zSH/h9f6TibN9A/XGxGOxjWflP69Md9CpxGANZc/N940vyRTwdfmHTPcaCkCAwEA
#                AQKCAgA8NuR76ijHhnvWt0L33HUcEVeq93GHH5z2Ay5f/TYJjHma4YgxStf1b6Tu
#                dSllp3G5LvsdBh31CtPIIRvDDomCYCpNBU2ggcLP0I9ozRU7QjHxz3VM3mZbN+FG
#                sVlnpDeYhS9cUb9b6vblTLJ6bU60uSMWW5HLLvQX79gbFI9yf/YSyfCWK/l0yXoL
#                u87w4Q6OxzvBE8doWaMJwbHkgu+oMPlEuOTb50gWEgBJfsMiVOvcICPnCA6Nrl/D
#                8zq26DckhlsgryKx+6blN61Yiyr8Gk1aaTQXKTwe+JSssaX6BtISCS5QtGcu8TYc
#                ybc6RjAqsoJAegEY6aj13yAUdyPNA75C52KYUCBvqK/yNqAlYrQxv+w9bRpU6Rku
#                Y3mWf59G+LCnbb3NmXcG4C1jiQa9a35kV3TWXN5y0Nl8JiFqLJrRd4Qwi2oIuGAs
#                uKoYZAwakvVOu/5HDFtblAGNB3WCqNpLbIxGCABW4KsDb93OMjZ0pZH2VsUZQ7cS
#                C/MT9geAcssYyqocIM5oHtkdAAh54QsIbdt6CVfgeljsfikutKGLiQHk0e1ANgXd
#                8Q1w61vmVDZLD2cfB/LT1Mu+DoKC1uKrb60KqPFrUZCVHtlV99+SlJ+6fk66tQhv
#                n1wNYwdj8WRm+z7QAEsbvsP308FSd1e3naRauSQ3wS3SlbHZIQKCAQEA2GdutfIW
#                U9e2lzB6j0SsfVhX8gRDTzm+g/YjDR4VReVFu0zQefwHtm+/nHrY7YqQG23YYfVX
#                pMPPIa7k1IbHC0uLGXDhnEO8dtUlw+ojY77S1URIeqfsx8tDxEjMIQpOm4YB+htz
#                Z49VLvjGQ/SYvcryyXRO6znSehBzlOfMpqaWXgaxrN/zOgjzz6zR1/TC4Wir7uZP
#                mKRJ6zw+g/j2/gNV8qLriK4i/n9l19Kh/8UVP09Ab9qKis/yGWG08XktWTDuZHq6
#                KhDhEO/9yuEdv/SDDQQp3yeIHmhf7WCEoxC1ezyGnAQlYp20pGDa0vxuvJdebTUb
#                QzpWcimnCRO4FQKCAQEAzyGvtOrolX6cyb1OWerBuNCfzUa/tCBbOjIRinlUlyR0
#                Jyv3l+A4aisO5CedROfe7Xdnnt7I2Fck7GBuTkWzEU+CdToAH2/99xEb9ZRCeB3I
#                pwx5grDyXWkWvMNF9oupI6oN78fYTRcgDaK1kO+e2YGPqh3wIYwFx5JKQ4T9OdPx
#                4qbEpVnZY1rAjxUJZBDTPyiNAv8/ihnRsz9QOU0Pmu3sejLLbvoKqpVxYOtE+Dcq
#                Fvo24l+bjDAEEpMBGIolx6Td3uCNEasedf9Gurqq/HojS35kcpqmp0rdHt/xshlZ
#                VW/j3zzZpCEreOc4cwYaTzz6EhBVSJaO7xbPfyDAxQKCAQAPDqNVZZLIIqpBus3M
#                Sir2Tb9Qx5snWA05gVbPAtjYFCvV7HJVCoQ+3Wenq6SMYqfEQNBdgISoojc3UMP7
#                RaVz073J92C7Trs+SXZnO1NbDVv+GtIwNp7zB+GfNrF9Wwo9KAXbMS3GduKmcgjZ
#                kZtPGV/rRHx5QXyzoZFpOveyYMT1peGW9b4mu5i7SnsPW6hzpqTP6pZ/OG8sPvTa
#                megVpIXGbC+XQwaMTrD3Y2CCO2RPE2SYY8xf/DgMLBA6/QN6wTzVIPTzGFmQpCI0
#                i5VWVd0IetGvBUEjXH/QNHcGIZN/D6cOE/vF8NMw3MxdAdNyq9WWI6vR8a0yJFPK
#                /eRBAoIBABzIbpUya32SqZDzKHcgQyk+fGZXJX6PXH36xSs77wBNxYJH/tDxDIXc
#                U+ZqhtUzb2wKQrD1/mzptyzNvaZM0zRdmyBVHf1AX8c8bmky4AW3BdIIzr3Vfuhy
#                GQHEFO3MvIVDNUqTt8AGraKXcKmiUq2g7mjSXjMbNRZlgsJdMZ8ej6dSS1M66BWB
#                X+7CGpr4J5LIPMgk1hyHt/cznh9IURnTZCAa/OAACQlpWOcB6oSfjc7BmGzeokvZ
#                xEccfHN/hv52L4qwI4pIACSfg6GhHO+WvV7ZQnYWfYATzCRlND3ufdZ8hOrZltjS
#                7yqO3u5E89T9ATcPY/qBSX156v2cfI0CggEAda4YuE3vnBA46s8MO98uMK3wagbp
#                f2W1BjR1spBJv6Pkt77l+JQqMDkFEh3sOSFBRqDQbqmTFf8up1dKn/FA1Q9+NA91
#                oBz+faVV5f4pvhQrEWHiujYl2LzFa8Qp4epC5AuWgjEV2cfAXuGR4g5R7eYXQroD
#                wiwSpJFGarZ+/i+gQct/QP4SjCApIbQCgQFvyuQIFuZvkNZhxKMdkJY3S15iy1u2
#                DAP7jpbX0MgTEcOcAqztOkQ/r1pdc3yy1Zk2h1TRu3UsqlmIt+j+zUNQ2TRL5a1J
#                KZHY2Ty2t4JlfkmilzugFR7ADaXvO1++xyEMx4t9RzClbJSukG60fSPRew==
#                -----END RSA PRIVATE KEY-----
